version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db-taskmanager
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"